---
title: "EJ_wells_CV"
author: "Claire Madden"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(maptools)
library(ggspatial)
library(tmap)
library(sf)
library(ggrepel)
library(RColorBrewer)
library(stringr)
library(janitor)
```




```{r}

all_wells <- read_csv("OSWCR.csv")

dry_wells <- read_sf("All_drywells.shp") %>% 
  st_transform(crs = 4326) # set projection

ces <- read_sf("CESsimple.shp")%>% 
  st_transform(crs = 4326) # redefine projection 

ca <- read_sf("California.shp")%>% 
  st_transform(crs = 4326) 

cv <- read_sf("SGMA_Dissolved_Central_Valley.shp")%>% 
  st_transform(crs = 4326)



ggplot(data = ces)+
  geom_sf()
# check that ces maps correctly



```


```{r}

# get a clean and simple version of domestic well locations ready to turn into spatial data

dom_wells <- all_wells %>% 
  select(WCRNumber, DecimalLatitude, DecimalLongitude, PlannedUseFormerUse) %>% 
  clean_names() %>% 
  mutate(use = str_to_lower(planned_use_former_use)) %>% 
  filter(str_detect(use, "domestic")) %>% 
  select(-planned_use_former_use) %>% 
  drop_na(decimal_latitude)


```









